### ISSUE TITLE
allow providing command as parameter — e.g.: up grep

### ISSUE THREAD

**Issue by pannous** [akavel/up#11]
please allow giving command to up as parameter (also to avoid the rm nightmare)

**Comment by akavel** [comment]
Thanks for the idea! I'd like to actually do this indeed at some point in future.

**Comment by puffnfresh** [comment]
This would work for my ghci stuff.

**Comment by akavel** [comment]
Note to self: because we now support various different shells (which have different standards for quoting), the full pipeline would have to be passed as a single argument (in quotes). For symmetry with a convention that seems popular among Linux tools, I think it would be a good idea then to pass it via a "-c" flag. Example call would then look like below:

    $ lshw |& up -c "grep network -A2 | grep :"

---

@puffnfresh Does the $SHELL discovery feature added in [v0.3](https://github.com/akavel/up/releases/v0.3) work for you for ghci?
