### ISSUE TITLE
Mention AUR in installation methods

### ISSUE THREAD

**Issue by gunar** [akavel/up#30]
Someone already created a PKGBUILD for `up` so it's just a matter of `yaourt -Syy up` to install Ultimate Plumber on Arch/Manjaro systems. Thanks a bunch!

**Comment by akavel** [comment]
Related: #17

**Comment by sector-f** [comment]
@gunar I don't think recommending yaourt is a good idea.
* it isn't under active development anymore 
* it was never good in the first place

And it's worth noting that `yaourt -Syy package` (or even `pacman -Syy package`) is dangerous on Arch since you're refreshing your package database without doing a full system upgrade; see [this](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) for more information.

Also, AUR helpers aren't officially supported anyways. It's probably best to just state that there's an AUR package. That should be enough information for an Arch user to get it installed.

**Comment by gunar** [comment]
_(pardon my off-topicness)_

@sector-f welp, guess you're right, and now I've learned something. So what's the alternative to AUR helpers? Somehow getting notified of new versions then manually downloading and installing the code?

**Comment by pablox-cl** [comment]
@gunar , you can always download the PKGBUILD by hand, and then build it or since AUR4 clone it with git. Besides that, I agree with @sector-f that only having the link / name to the aur pkg is enough :)

**Comment by sector-f** [comment]
@gunar Oh, there's nothing inherently wrong with using package managers. It's just that they're not officially supported and so I don't think recommending a specific one is a good idea.

Consider asking the #archlinux IRC channel on Freenode for AUR helper suggestions; I'm sure they keep up with that stuff more than I do.

**Comment by milkmiruku** [comment]
https://github.com/Jguer/yay
